name: Test Slow Functions

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  schedule:
    - cron: "0 5 1,15 * *"

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  test-slow:
    runs-on: ${{ matrix.os }}
    defaults:
      run:
        shell: bash -e {0} # -e to fail on error

    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest]
        python: ["3.12"]
        group: [1, 2, 3]

    name: ${{ matrix.name }} Python ${{ matrix.python }} (group ${{ matrix.group }}/3)

    env:
      OS: ${{ matrix.os }}
      PYTHON: ${{ matrix.python }}

    steps:
      - uses: actions/checkout@v4
      - name: Set up Python ${{ matrix.python }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python }}
          cache: "pip"
          cache-dependency-path: "**/pyproject.toml"

      - name: Install test dependencies
        run: |
          python -m pip install --upgrade pip wheel
      - name: Install dependencies
        run: |
          pip install tox
          pip install ${{ matrix.pip-flags }} ".[optional-dependencies.dev,optional-dependencies.test,optional-dependencies.external,optional-dependencies.docs,optional-dependencies.embedding]"
          pip install wandb omegaconf
      - name: Test slow functions
        run: |
          tox -e py-${{ matrix.python }} -- -m "slow" --splits 3 --group ${{ matrix.group }} --splitting-algorithm least_duration
        env:
          PYTEST_ADDOPTS: -vv

      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v5
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          slug: theislab/cellflow
