[datasets]
txpert_pathway3352_allcovered_fixed2000 = "outputs/state_eval_data/txpert_pathway3352_k562_allcovered_fixed2000"

[training]
txpert_pathway3352_allcovered_fixed2000 = "train"

[zeroshot]
"txpert_pathway3352_allcovered_fixed2000.K562" = "test"

[fewshot]
