[datasets]
txpert_pathway3352_known55 = "external/third-party/state_py39/eval_data/txpert_pathway3352_k562_known55"

[training]
txpert_pathway3352_known55 = "train"

[zeroshot]
"txpert_pathway3352_known55.K562" = "test"

[fewshot]
