[project]
name = "arc-state"
version = "0.11.2"
description = "State is a machine learning model that predicts cellular perturbation response across diverse contexts."
readme = "README.md"
authors = [
    { name = "Abhinav Adduri", email = "abhinav.adduri@arcinstitute.org" },
    { name = "Yusuf Roohani", email = "yusuf.roohani@arcinstitute.org" },
    { name = "Noam Teyssier", email = "noam.teyssier@arcinstitute.org" },
    { name = "Rajesh Ilango", email = "rilango@gmail.com" },
    { name = "Dhruv Gautam", email = "dhruvgautam@berkeley.edu" },
]
requires-python = ">=3.9,<3.13"
dependencies = [
    "anndata>=0.10.9,<0.11; python_version < '3.10'",
    "anndata>=0.11.4; python_version >= '3.10'",
    "cell-load>=0.10.4; python_version >= '3.10'",
    "numpy>=1.26.4,<2.1; python_version < '3.10'",
    "numpy>=2.2.6; python_version >= '3.10'",
    "pandas>=1.5.3; python_version < '3.10'",
    "pandas>=2.2.3; python_version >= '3.10'",
    "pyyaml>=6.0.2",
    "scanpy>=1.10.3,<1.10.4; python_version < '3.10'",
    "scanpy>=1.11.2; python_version >= '3.10'",
    "scikit-learn>=1.6.1",
    "seaborn>=0.13.2",
    "torch>=2.6.0; python_version < '3.10'",
    "torch>=2.7.0; python_version >= '3.10'",
    "tqdm>=4.67.1",
    "wandb>=0.19.11",
    "hydra-core>=1.3.2",
    "geomloss>=0.2.6",
    "transformers>=4.52.3",
    "peft>=0.11.0",
    "ipykernel>=6.30.1,<7; python_version < '3.10'",
    "ipykernel>=6.30.1; python_version >= '3.10'",
    "scipy>=1.13.1,<1.14; python_version < '3.10'",
    "scipy>=1.15.0; python_version >= '3.10'",
]

[project.optional-dependencies]
eval = [
    "cell-eval>=0.8.1; python_version >= '3.11'",
]
vectordb = [
    "lancedb>=0.24.0"
]

[dependency-groups]
dev = ["ruff>=0.11.11", "vulture>=2.14", "ipython>=8.37.0"]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project.scripts]
state = "state.__main__:main"

[tool.pyright]
venvPath = "."
venv = ".venv"

[tool.hatch.build.targets.wheel]
packages = ["src/state"]
